---
- hosts: shutdown
  gather_facts: no
  become: yes
  tasks:
    - name: shutdown
      ansible.builtin.command: /usr/sbin/shutdown -h now

    - name: wait go down
      local_action: wait_for host={{ ansible_ssh_host }} port=22 state=stopped