---
- name: poweroff
  hosts: LinuxVM
  become: yes
  gather_facts: no
  tasks:
    - name: apagado
      ansible.builtin.command: /usr/sbin/shutdown -h +2 "prueba de apagado"

    #- name: wait go down
    #  local_action: wait_for host={{ ansible_ssh_host }} port=22 state=stopped
    #- name: apagadotest
    #  community.general.shutdown:
    #    delay: 10