---
- name: poweroff
  hosts: LinuxVM
  remote_user: adminscu
  #become_user: adminscu
  become: yes
  #become_method: sudo
  gather_facts: no
  tasks:
    - name: apagado
      ansible.builtin.command: /usr/sbin/shutdown -h now

    - name: wait go down
      local_action: wait_for host={{ ansible_ssh_host }} port=22 state=stopped
    #- name: apagadotest
    #  community.general.shutdown:
    #    delay: 10